### ISSUE TITLE
Unable to install through HACS

### ISSUE THREAD

**Issue by tslpre** [bzzoiro/repsolluzygas#5]
For some reason, this component does not install through HACS. Comparing it with my fork (which I tested and it works), I've noticed that in hacs.json there were two different "version" keys. I've removed the extra/wrong one.

Will try to publish it again (not sure I've got the rights) and see if that was the culprit...

**Comment by tslpre** [comment]
Pending validation...

**Comment by bzzoiro** [comment]
In my case isn't working yet.

I see that this component is trying to install under "/config/custom_components/repsolluzygas", while other components are installing directly in custom_components root '/config/custom_components/'

screenshot for reference from another component:

![Screenshot from 2021-09-13 15-51-06](https://user-images.githubusercontent.com/9134036/133096075-2c84843f-e240-44de-9dcf-8ae6fceafdcc.png)

**Comment by bzzoiro** [comment]
Working like a charm. Nice job @tslpre . Thanks
